# Generated by Django 3.2.5 on 2021-08-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(null=True, unique=True, upload_to='')),
                ('categorie', models.CharField(max_length=50, null=True)),
                ('tags', models.CharField(max_length=300, null=True)),
                ('ref', models.CharField(max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='bonplan',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_des_bn_plan.publication')),
                ('tel', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('adresse', models.TextField(unique=True)),
            ],
            bases=('gestion_des_bn_plan.publication',),
        ),
    ]
